<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="48800" started-at="2022-08-04T03:14:05Z" finished-at="2022-08-04T03:14:54Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="48800" started-at="2022-08-04T03:14:05Z" finished-at="2022-08-04T03:14:54Z">
      <class name="testcases.HowToTakeScreenShotOnFailure">
        <test-method status="PASS" signature="start()[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643]" name="start" is-config="true" duration-ms="5607" started-at="2022-08-04T03:14:05Z" finished-at="2022-08-04T03:14:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="takeScreenshotOnFailure()[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643]" name="takeScreenshotOnFailure" duration-ms="17298" started-at="2022-08-04T03:14:11Z" finished-at="2022-08-04T03:14:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshotOnFailure -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643]" name="tearDown" is-config="true" duration-ms="6" started-at="2022-08-04T03:14:28Z" finished-at="2022-08-04T03:14:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=takeScreenshotOnFailure status=SUCCESS method=HowToTakeScreenShotOnFailure.takeScreenshotOnFailure()[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="start()[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643]" name="start" is-config="true" duration-ms="3719" started-at="2022-08-04T03:14:28Z" finished-at="2022-08-04T03:14:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="takeScreenshotOnFailure2()[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643]" name="takeScreenshotOnFailure2" duration-ms="21656" started-at="2022-08-04T03:14:32Z" finished-at="2022-08-04T03:14:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testcases.HowToTakeScreenShotOnFailure.takeScreenshotOnFailure2(HowToTakeScreenShotOnFailure.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshotOnFailure2 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643]" name="tearDown" is-config="true" duration-ms="411" started-at="2022-08-04T03:14:53Z" finished-at="2022-08-04T03:14:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=takeScreenshotOnFailure2 status=FAILURE method=HowToTakeScreenShotOnFailure.takeScreenshotOnFailure2()[pri:0, instance:testcases.HowToTakeScreenShotOnFailure@2d928643] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.HowToTakeScreenShotOnFailure -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
